### ISSUE TITLE
Imported cards sometimes don't add up correctly.

### ISSUE THREAD

**Issue by Rvtar** [Tyrannicodin/scuffed-tcg-site#11]
[GPO.csv](https://github.com/Tyrannicodin/scuffed-tcg-site/files/14228995/GPO.csv)
[he_dump.csv](https://github.com/Tyrannicodin/scuffed-tcg-site/files/14228996/he_dump.csv)
[effects_remigrate.csv](https://github.com/Tyrannicodin/scuffed-tcg-site/files/14228997/effects_remigrate.csv)
[effects_migrate.csv](https://github.com/Tyrannicodin/scuffed-tcg-site/files/14228998/effects_migrate.csv)

When importing cards, some cards get added to the collection by the wrong amount. Some are missing, but most of the errors I noticed are cards being added by a comically large number. I managed to replicate most of the errors.

The csvs given are my cards that I imported to the database. I did it from the bottom file up.

**Comment by Tyrannicodin** [comment]
Not sure what's up with this, will ask Benji to take a look.

**Comment by Rvtar** [comment]
I just tried another sequence and things broke differently.

**Comment by Rvtar** [comment]
One piece of info I forgot: On my main and first test account, I bought cards and packs from the shop first and ended up with 22 sandpaper. In my second test account, I did the importing first and ended up with 17 sandpaper. I did the same import sequence on all 3 accounts.

**Comment by Benji42** [comment]
I think this is fixed as I made some changes to how card importing works and cannot replicate anymore. Let me know if you find issues again.

**Comment by Rvtar** [comment]
Still broken (Anvil×19 etc.)
