### ISSUE TITLE
Tried importing double item cards but failed

### ISSUE THREAD

**Issue by PandaMask** [Tyrannicodin/scuffed-tcg-site#12]
Tried to import my double item cards to the site but failed. Somehow, only 1 scavenger double item card was imported successfully.

My sheet was formatted this way:

Column 1
Item card name x2

Column 2
Rare

I didn't feel the need to add a 3rd column to specify the number of cards I had, because the site said that was optional.

**Screenshots**
![Screenshot_1](https://github.com/Tyrannicodin/scuffed-tcg-site/assets/159621586/3cbf1932-e185-4073-a11a-3ae198bfcd35)
![Screenshot_2](https://github.com/Tyrannicodin/scuffed-tcg-site/assets/159621586/114ad461-b6a2-4b74-917b-f56389a577de)

 - OS: Windows
 - Browser: Chrome

**Comment by Rvtar** [comment]
To my knowledge, using that format with Chrome on Windows shouldn't yield a single card.

**Comment by PandaMask** [comment]
> To my knowledge, using that format with Chrome on Windows shouldn't yield a single card.

I was told the rarity of double item cards is rare. I was also told the 3rd column is optional.

**Comment by Tyrannicodin** [comment]
That is correct, this is a bug. Also it's Benji's problem

**Comment by Benji42** [comment]
Fixed this, yay
