### ISSUE TITLE
Deleted account still exists.

### ISSUE THREAD

**Issue by Rvtar** [Tyrannicodin/scuffed-tcg-site#13]
I deleted a test account properly then I tried to remake the account, only to find out that the username had already been taken. I attempted to login, and I successfully logged into a deleted account lmao.

**Comment by Rvtar** [comment]
And most importantly, everything worked perfectly fine.

**Comment by Tyrannicodin** [comment]
I'm pretty sure I know what the issue is here. SQL foreign keys prevent us from deleting users with cards in other tables. Will attempt to replicate and fix tonight.
