### ISSUE TITLE
Authentication is skippable.

### ISSUE THREAD

**Issue by Rvtar** [Tyrannicodin/scuffed-tcg-site#15]
You can interrupt the authentication and the account is still set up.

**Comment by Rvtar** [comment]
Maybe add an OTP requirement as a step to set up an account?

**Comment by Tyrannicodin** [comment]
There should be, not sure why it keeps the account after you fail authentication.

**Comment by Rvtar** [comment]
Maybe the deletion failed?

**Comment by Tyrannicodin** [comment]
no, but I've figured it out now. Making a PR now
